{
 "title": "RDS instances",
 "description": "RDS instances inventory",
 "tags": [
  "dmf",
  "server"
 ],
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "label": "Data source", "query": "prometheus" },
   {
    "name": "aws_account_id",
    "label": "Account",
    "query": "label_values(rds_instance_info, aws_account_id)"
   },
   {
    "name": "aws_region",
    "label": "Region",
    "query": "label_values(rds_instance_info{aws_account_id=~\"$aws_account_id\"}, aws_region)"
   }
  ]
 },
 "panels": [
  { "title": "Overview", "type": "row", "gridPos": { "h": 1, "w": 0, "x": 0, "y": 0 } },
  {
   "title": "Instances",
   "type": "stat",
   "description": "Number of AWS RDS instances in selected AWS account(s) and region(s)",
   "gridPos": { "h": 3, "w": 3, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "count(rds_instance_info{aws_account_id=~\"$aws_account_id\",aws_region=~\"$aws_region\"})\n"
    }
   ]
  },
  {
   "title": "Pending maintenances",
   "type": "stat",
   "description": "Total number of RDS instances with a pending maintenance",
   "gridPos": { "h": 3, "w": 3, "x": 3, "y": 1 },
   "targets": [
    {
     "expr": "count(rds_instance_info{aws_account_id=~\"$aws_account_id\",aws_region=~\"$aws_region\",pending_maintenance!=\"no\"} > 0)\n"
    }
   ]
  },
  {
   "title": "Pending modifications",
   "type": "stat",
   "description": "Total number of RDS instances with a pending modification",
   "gridPos": { "h": 3, "w": 3, "x": 6, "y": 1 },
   "targets": [
    {
     "expr": "count(rds_instance_info{aws_account_id=~\"$aws_account_id\",aws_region=~\"$aws_region\",pending_modified_values!=\"false\"})\n"
    }
   ]
  },
  {
   "title": "Deprecated certificates",
   "type": "stat",
   "description": "Total number of RDS instances with deprecated certificate",
   "gridPos": { "h": 3, "w": 3, "x": 9, "y": 1 },
   "targets": [
    {
     "expr": "count(rds_instance_info{aws_account_id=~\"$aws_account_id\",aws_region=~\"$aws_region\", ca_certificate_identifier!=\"rds-ca-rsa2048-g1\"})\n"
    }
   ]
  },
  {
   "title": "Standard support ending soon",
   "type": "stat",
   "description": "Total number of RDS instances with standard support ending soon",
   "gridPos": { "h": 3, "w": 3, "x": 12, "y": 1 },
   "targets": [
    {
     "expr": "count(\n  rds_standard_support_engine_remaining_days{aws_account_id=~\"$aws_account_id\",aws_region=~\"$aws_region\"} < 90\n  and\n  rds_standard_support_engine_remaining_days{aws_account_id=~\"$aws_account_id\",aws_region=~\"$aws_region\"} > 0\n  )\n"
    }
   ]
  },
  {
   "title": "Extended support",
   "type": "stat",
   "description": "Total number of RDS instances running with extended support",
   "gridPos": { "h": 3, "w": 3, "x": 15, "y": 1 },
   "targets": [
    {
     "expr": "count(rds_standard_support_engine_remaining_days{aws_account_id=~\"$aws_account_id\",aws_region=~\"$aws_region\"} < 0)\n"
    }
   ]
  },
  { "title": "Pending operations", "type": "row", "gridPos": { "h": 1, "w": 0, "x": 18, "y": 4 } },
  {
   "title": "Instances with pending maintenance",
   "type": "table",
   "description": "RDS instances with pending maintenance",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 5 },
   "targets": [
    {
     "expr": "rds_instance_info{aws_account_id=~\"$aws_account_id\",aws_region=~\"$aws_region\",pending_maintenance!=\"no\"}\n"
    }
   ]
  },
  {
   "title": "Instances with pending modification",
   "type": "table",
   "description": "RDS instances with pending modification",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 5 },
   "targets": [
    {
     "expr": "rds_instance_info{aws_account_id=~\"$aws_account_id\",aws_region=~\"$aws_region\",pending_modified_values!=\"false\"}\n"
    }
   ]
  },
  { "title": "Standard and extended support", "type": "row", "gridPos": { "h": 1, "w": 0, "x": 24, "y": 10 } },
  {
   "title": "Instances with standard support ending soon",
   "type": "table",
   "description": "RDS instances with standard support will be ending in the near future.",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 11 },
   "targets": [
    {
     "expr": "rds_standard_support_engine_remaining_days{aws_account_id=~\"$aws_account_id\",aws_region=~\"$aws_region\"} < 90\nand\nrds_standard_support_engine_remaining_days{aws_account_id=~\"$aws_account_id\",aws_region=~\"$aws_region\"} > 0\n"
    }
   ]
  },
  {
   "title": "Instances with extended support",
   "type": "table",
   "description": "RDS instances running in extended support",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 11 },
   "targets": [
    {
     "expr": "rds_extended_support_engine_remaining_days{aws_account_id=~\"$aws_account_id\",aws_region=~\"$aws_region\"}\nand on (aws_account_id, aws_region, dbidentifier)\n(\n  rds_standard_support_engine_remaining_days{aws_account_id=~\"$aws_account_id\",aws_region=~\"$aws_region\"} < 0\n)\n"
    }
   ]
  },
  { "title": "Inventory", "type": "row", "gridPos": { "h": 1, "w": 0, "x": 24, "y": 16 } },
  {
   "title": "RDS instances",
   "type": "table",
   "description": "List of RDS instances in selected AWS account(s) and region(s)",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 17 },
   "targets": [
    {
     "expr": "rds_instance_info{aws_account_id=~\"$aws_account_id\",aws_region=~\"$aws_region\"} * on (dbidentifier) group_left max(rds_allocated_storage_bytes{}) by (dbidentifier)\n"
    }
   ]
  },
  { "title": "AWS Quota", "type": "row", "gridPos": { "h": 1, "w": 0, "x": 24, "y": 24 } },
  {
   "title": "RDS instance quota usage (ratio)",
   "type": "timeseries",
   "description": "Ratio of used RDS instances regarding AWS quota",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "count(\n    count(rds_instance_info{aws_account_id=~\"$aws_account_id\",aws_region=~\"$aws_region\"}) by (aws_account_id, aws_region, dbidentifier)\n) by (aws_account_id, aws_region)\n* 100\n/\nsum(\n    max(rds_quota_max_dbinstances_average{aws_account_id=~\"$aws_account_id\",aws_region=~\"$aws_region\"}) by (aws_account_id, aws_region)\n) by (aws_account_id, aws_region)\n",
     "legendFormat": "{{ aws_account_id }}:{{ aws_region }}"
    }
   ]
  },
  {
   "title": "RDS storage quota usage (ratio)",
   "type": "timeseries",
   "description": "Ratio of used RDS storage regarding AWS quota",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "sum(\n    max(rds_allocated_storage_bytes{aws_account_id=~\"$aws_account_id\",aws_region=~\"$aws_region\"}) by (aws_account_id, aws_region, dbidentifier)\n) by (aws_account_id, aws_region)\n* 100\n/\nsum(\n    max(rds_quota_total_storage_bytes{aws_account_id=~\"$aws_account_id\",aws_region=~\"$aws_region\"}) by (aws_account_id, aws_region)\n) by (aws_account_id, aws_region)\n",
     "legendFormat": "{{ aws_account_id }}:{{ aws_region }}"
    }
   ]
  },
  {
   "title": "RDS instance quota",
   "type": "timeseries",
   "description": "The number of instances regarding your RDS instances quota. You can request a quota increase to AWS",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 33 },
   "targets": [
    {
     "expr": "sum(\n    max(rds_quota_max_dbinstances_average{aws_account_id=~\"$aws_account_id\",aws_region=~\"$aws_region\"}) by (aws_account_id, aws_region)\n) by (aws_account_id, aws_region)\n",
     "legendFormat": "Max {{ aws_account_id }}:{{ aws_region }}"
    },
    {
     "expr": "count(\n    count(rds_instance_info{aws_account_id=~\"$aws_account_id\",aws_region=~\"$aws_region\"}) by (aws_account_id, aws_region, dbidentifier)\n) by (aws_account_id, aws_region)\n",
     "legendFormat": "Total {{ aws_account_id }}:{{ aws_region }}"
    }
   ]
  },
  {
   "title": "RDS storage quota",
   "type": "timeseries",
   "description": "The total storage used regarding your RDS total storage quota. You can request a quota increase to AWS",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 33 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(\n    max(rds_quota_total_storage_bytes{aws_account_id=~\"$aws_account_id\",aws_region=~\"$aws_region\"}) by (aws_account_id, aws_region)\n) by (aws_account_id, aws_region)\n",
     "legendFormat": "Max {{ aws_account_id }}:{{ aws_region }}"
    },
    {
     "expr": "sum(\n    max(rds_allocated_storage_bytes{aws_account_id=~\"$aws_account_id\",aws_region=~\"$aws_region\"}) by (aws_account_id, aws_region, dbidentifier)\n) by (aws_account_id, aws_region)\n",
     "legendFormat": "Total {{ aws_account_id }}:{{ aws_region }}"
    }
   ]
  }
 ]
}