{
 "title": "RDS cluster details",
 "description": "RDS cluster details",
 "tags": [
  "dmf",
  "server"
 ],
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "datasource",
    "label": "Data source",
    "query": "grafana-amazonprometheus-datasource"
   },
   {
    "name": "aws_account_id",
    "label": "Account",
    "query": "label_values(rds_instance_info, aws_account_id)"
   },
   {
    "name": "aws_region",
    "label": "Region",
    "query": "label_values(rds_instance_info{aws_account_id=~\"$aws_account_id\"}, aws_region)"
   },
   {
    "name": "cluster_identifier",
    "label": "Cluster",
    "query": "label_values(rds_cluster_info{aws_account_id=~\"$aws_account_id\", aws_region=~\"$aws_region\"}, cluster_identifier)"
   }
  ]
 },
 "panels": [
  { "title": "Overview", "type": "row", "gridPos": { "h": 1, "w": 0, "x": 0, "y": 0 } },
  {
   "title": "Engine",
   "type": "stat",
   "description": "Engine",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "rds_cluster_info{aws_account_id=\"$aws_account_id\",aws_region=\"$aws_region\",cluster_identifier=\"$cluster_identifier\"}\n"
    }
   ]
  },
  {
   "title": "Engine Version",
   "type": "stat",
   "description": "Cluster engine version",
   "gridPos": { "h": 3, "w": 3, "x": 4, "y": 1 },
   "targets": [
    {
     "expr": "rds_cluster_info{aws_account_id=\"$aws_account_id\",aws_region=\"$aws_region\",cluster_identifier=\"$cluster_identifier\"}\n"
    }
   ]
  },
  {
   "title": "ACU",
   "type": "stat",
   "description": "Number of current Aurora Capacity Units used by this cluster",
   "gridPos": { "h": 3, "w": 3, "x": 7, "y": 1 },
   "targets": [
    {
     "expr": "sum by (cluster_identifier) (\n  rds_serverless_instance_acu_average\n    * on(dbidentifier)\n      group_left(cluster_identifier)\n      (rds_instance_info{aws_account_id=\"$aws_account_id\",aws_region=\"$aws_region\",cluster_identifier=\"$cluster_identifier\"})\n)\n",
     "legendFormat": "Current ACU"
    }
   ]
  },
  {
   "title": "Instances",
   "type": "stat",
   "description": "Number of instances in the cluster",
   "gridPos": { "h": 3, "w": 3, "x": 10, "y": 1 },
   "targets": [
    {
     "expr": "count(rds_instance_info{aws_account_id=~\"$aws_account_id\",aws_region=~\"$aws_region\",cluster_identifier=~\"$cluster_identifier\"})\n"
    }
   ]
  },
  {
   "title": "Instance classes",
   "type": "stat",
   "description": "Number of instances by instance class type",
   "gridPos": { "h": 3, "w": 11, "x": 13, "y": 1 },
   "targets": [
    {
     "expr": "sum(rds_instance_info{aws_account_id=~\"$aws_account_id\",aws_region=~\"$aws_region\",cluster_identifier=~\"$cluster_identifier\"}) by (instance_class)\n",
     "legendFormat": "{{ instance_class }}"
    }
   ]
  },
  { "title": "Inventory", "type": "row", "gridPos": { "h": 1, "w": 0, "x": 24, "y": 4 } },
  {
   "title": "Instances",
   "type": "table",
   "description": "List of RDS instances in the clusters",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 5 },
   "targets": [
    {
     "expr": "rds_instance_info{aws_account_id=~\"$aws_account_id\",aws_region=~\"$aws_region\",cluster_identifier=~\"$cluster_identifier\"}\n"
    }
   ]
  },
  { "title": "Serverless", "type": "row", "gridPos": { "h": 1, "w": 0, "x": 24, "y": 12 } },
  {
   "title": "Configuration",
   "type": "stat",
   "description": "Minimum/Maximum number of Aurora capacity units (ACUs) for a DB instance in an Aurora Serverless v2 cluster.",
   "gridPos": { "h": 5, "w": 2, "x": 0, "y": 13 },
   "targets": [
    {
     "expr": "rds_cluster_acu_min_average{aws_account_id=\"$aws_account_id\",aws_region=\"$aws_region\",cluster_identifier=\"$cluster_identifier\"}\n",
     "legendFormat": "Min ACU/instance"
    },
    {
     "expr": "rds_cluster_acu_max_average{aws_account_id=\"$aws_account_id\",aws_region=\"$aws_region\",cluster_identifier=\"$cluster_identifier\"}\n",
     "legendFormat": "Max ACU/instance"
    }
   ]
  },
  {
   "title": "Autoscaling ACU usage",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 22, "x": 2, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "max by (cluster_identifier) (\n  rds_serverless_instance_acu_average\n    * on(dbidentifier)\n      group_left(cluster_identifier)\n      (rds_instance_info{aws_account_id=\"$aws_account_id\", aws_region=\"$aws_region\", cluster_identifier=\"$cluster_identifier\"})\n)\n* 100\n/ \nmax by (cluster_identifier) (rds_cluster_acu_max_average{aws_account_id=\"$aws_account_id\", aws_region=\"$aws_region\", cluster_identifier=\"$cluster_identifier\"})\n",
     "legendFormat": "{{cluster_identifier}}"
    }
   ]
  },
  {
   "title": "ACU per instance",
   "type": "timeseries",
   "description": "TODO",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 20 },
   "targets": [
    {
     "expr": "rds_serverless_instance_acu_average\n    * on(dbidentifier)\n      group_left(cluster_identifier)\n      (rds_instance_info{aws_account_id=\"$aws_account_id\",aws_region=\"$aws_region\",cluster_identifier=\"$cluster_identifier\"})\n",
     "legendFormat": "{{dbidentifier}}"
    }
   ]
  }
 ]
}