{
 "title": "RDS clusters",
 "description": "RDS clusters inventory",
 "tags": [
  "dmf",
  "server"
 ],
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "label": "Data source", "query": "prometheus" },
   {
    "name": "aws_account_id",
    "label": "Account",
    "query": "label_values(rds_instance_info, aws_account_id)"
   },
   {
    "name": "aws_region",
    "label": "Region",
    "query": "label_values(rds_instance_info{aws_account_id=~\"$aws_account_id\"}, aws_region)"
   }
  ]
 },
 "panels": [
  { "title": "Overview", "type": "row", "gridPos": { "h": 1, "w": 0, "x": 0, "y": 0 } },
  {
   "title": "Clusters",
   "type": "stat",
   "description": "Number of AWS RDS clusters (Amazon Aurora or RDS Multi-AZ DB clusters) in selected AWS account(s) and region(s)",
   "gridPos": { "h": 5, "w": 3, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "count(rds_cluster_info{aws_account_id=~\"$aws_account_id\",aws_region=~\"$aws_region\"})\n"
    }
   ]
  },
  {
   "title": "Clusters by engine",
   "type": "piechart",
   "description": "Total number of cluster per engines in selected AWS account(s) and region(s)",
   "gridPos": { "h": 5, "w": 8, "x": 3, "y": 1 },
   "targets": [
    {
     "expr": "sum(rds_cluster_info{aws_account_id=~\"$aws_account_id\",aws_region=~\"$aws_region\"}) by (engine)\n",
     "legendFormat": "{{ engine }}"
    }
   ]
  },
  { "title": "Inventory", "type": "row", "gridPos": { "h": 1, "w": 0, "x": 11, "y": 6 } },
  {
   "title": "RDS clusters",
   "type": "table",
   "description": "List of RDS clusters (Amazon Aurora or RDS Multi-AZ DB clusters) in selected AWS account(s) and region(s)",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 7 },
   "targets": [
    {
     "expr": "rds_cluster_info{aws_account_id=~\"$aws_account_id\",aws_region=~\"$aws_region\"}\n"
    }
   ]
  }
 ]
}